# config file version
apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://prometheus:9090
  # <bool> allow users to edit datasources from the UI.
  editable: true
  jsonData:
    timeInterval: 1s

  # <string, required> name of the datasource. Required
- name: tempo
  # <string, required> datasource type. Required
  type: tempo
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://tempo:3200
  # <bool> allow users to edit datasources from the UI.
  editable: true
  jsonData:
    tracesToLogsV2:
      datasourceUid: 'loki'

  # <string, required> name of the datasource. Required
- name: loki
  # <string, required> datasource type. Required
  type: loki
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://loki:3100
  # <bool> allow users to edit datasources from the UI.
  editable: true
